version: '3.9'

services:
  sqlserver-popa:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-popa
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./migrations:/migrations
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "sqlserver-popa", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT @@VERSION" ]
      interval: 10s
      retries: 10
      start_period: 60s

  migration-runner:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: migration-runner
    depends_on:
      sqlserver-popa:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: >
      /bin/bash -c "
      echo 'Aguardando o banco de dados estar totalmente pronto...';
      /migrations/wait-for-it.sh sqlserver-popa:1433 --timeout=300 --strict -- echo 'Banco de dados pronto!';
      for file in /migrations/*.sql; do
        echo 'Executando migration: \$file';
        /opt/mssql-tools/bin/sqlcmd -S sqlserver-popa -U sa -P YourStrong!Passw0rd -i \$file;
      done;
      echo '✅ Todas as migrations foram executadas';
      "
      
volumes:
  sqlserver_data:
