version: '3.9'

services:
  sqlserver-popa:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlserver-popa
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./migrations:/migrations
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "sqlserver-popa", "-U", "sa", "-P", "YourStrong!Passw0rd", "-Q", "SELECT @@VERSION" ]
      interval: 10s
      retries: 10
      start_period: 10s

  migration-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migration-runner
    depends_on:
      sqlserver-popa:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: >
      /bin/bash -c "
        echo 'Aguardando o banco de dados estar totalmente pronto...';
        /usr/local/bin/wait-for-it.sh sqlserver-popa:1433 --timeout=300 --strict -- echo 'Banco de dados pronto!';

        # Find migration files and store them in an array
        migration_files=(/migrations/*.sql)

        # Check if the array is empty (no files found)
        if [ \"$${migration_files[0]}\" = \"/migrations/*.sql\" ]; then
            echo '⚠️ Nenhum arquivo de migration encontrado.';
        else
            echo 'Iniciando a execução das migrations...';
            for file in \"$${migration_files[@]}\"; do
                echo 'Executando migration: '$$file'';
                /opt/mssql-tools/bin/sqlcmd -S sqlserver-popa -U sa -P 'YourStrong!Passw0rd' -i \"$$file\";
            done;
            echo '✅ Todas as migrations foram executadas';
        fi
        "

  popadin-api:
      build:
        context: .
        dockerfile: src/PopaDin.Bkd.Api/Dockerfile
      ports:
        - "5285:5285"
      environment:
        - ASPNETCORE_URLS=http://+:5285/
        - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      restart: unless-stopped

volumes:
  sqlserver_data:
